### ISSUE TITLE
Option to insert legend

### ISSUE THREAD

**Issue by jacopo-lupi** [BackgroundNose/EnergyLeveller#1]
Hi all, is there a way to insert a legend for different paths added in the graph? It would be really useful when one tries to compare a path calculated with different methods.

**Comment by JFurness1** [comment]
Hi there,

I haven't looked at this code in a long time but in principle there is no problem doing this.

Instead, I think it might be better to rewrite the rendering code to use matplotlib instead of the less common raw pango-cairo pdf drawing I used the first time.

Then legends would be 'free' as matplotlib can do them natively. 

If this code is useful to you I can certainly find some time to do this, hopefully in the next week or so. I didn't know anyone was using it! :)

James

**Comment by jacopo-lupi** [comment]
I'm using it since I haven't found similar stuffs to produce high-quality
PES for publication/scientific talk purposes.
Yeah, I think also that with matplotib would be better.

Thank you for the script!

Il giorno mer 27 mar 2019 alle ore 19:41 BackgroundNose <
notifications@github.com> ha scritto:

**Comment by JFurness1** [comment]
No problem! I'm happy to know it's useful for you.

This is why I wrote it in the first place. It seems strange to me that no program exists to plot nice to-scale PES given how common they are, but that does seem to be the case.

I'll put aside some time to make the changes then and push them here once they are ready.

**Comment by JFurness1** [comment]
Ok!

That should be updated. All seems to work by my tests.

I updated the example input to reflect the changes. Old inputs should still work, but they may make strange results as image size and label offsets are interpreted differently by matplotlib.

Let me know how it works for you and I'll close the issue. :)

**Comment by jacopo-lupi** [comment]
It works! Thank you very much :)
